### PR TITLE
add podspec file

### PR DESCRIPTION
**Pull request by therama**
Adding podspec file to publish **SwiftSubtitles** on Cocoapods dependency manager.
This process will release the module on the Cocoapods public spec repo.

This will release the latest version of **SwiftSubtitles** which is 0.8.1

This pod has dependencies on **DSFRegex** and **TinyCSV** which also need to be published on Cocoapods.
I will open separate pull requests for the dependency modules above.

Validation will not pass until those dependencies are made available.
Validating with command: `pod spec lint SwiftSubtitles.podspec --verbose` at the root of the project directory.

### CODE REVIEW

**Comment by therama** [comment]
Bumping watchOS version to 6.0 since I got the following error:
'CMTime' is only available in application extensions for watchOS 6.0 or newer

**Comment by dagronf** [comment]
Cocoapods is experiencing issues. I've registered DSFRegex and TinyCSV successfully (according to the emails) and just waiting for Cocoapods to start working again before I can continue

**Comment by dagronf** [comment]
I had to make some minor changes to these changes in the podspec, so I've pushed up a new version including your changes (v0.9.1)

All dependencies (TinyCSV, DSFRegex) have been updated with podspec support, and registered with cocoapods.

SwiftSubtitles has been updated with a podspec and registered with Cocoapods (v0.9.1)

https://github.com/CocoaPods/Specs/commit/e01d6de84c6d32e154f9e908c2dea0b5d55dc8c7

I'll close this pull request as it has been merged into another change (and it has been completed).

**Comment by dagronf** [comment]
Thank you!

**Pull request closed without merging**
